services:
  test.App\Service\CloudStorage\Storage\StorageInterface:
    alias: App\Service\CloudStorage\Storage\StorageInterface
    public: true

  test.App\Service\CloudStorage\Folder\FolderInterface:
    alias: App\Service\CloudStorage\Folder\FolderInterface
    public: true

  test.App\Service\CloudStorage\File\FileInterface:
    alias: App\Service\CloudStorage\File\FileInterface
    public: true
