services:
  test.App\Factory\CourseExamFactory:
    alias: App\Factory\CourseExamFactory
    public: true

  test.App\Factory\GoogleDriveFileFactory:
    alias: App\Factory\GoogleDriveFileFactory
    public: true
